### ISSUE TITLE
佬，有核酸检测和健康码的模拟吗？

### ISSUE THREAD

**Issue by popilong** [ilovexjp/trip-card#10]
总要去做检测太麻烦了，去哪都要24/48小时报告，md，每天下班不是先往家走，而是到亭子捅完喉咙再回家，真的烦人

**Comment by popilong** [comment]
总要去做检测太麻烦了，去哪都要24/48小时报告，md，每天下班不是先往家走，而是到亭子捅完喉咙再回家，真的烦人

**Comment by popilong** [comment]
> No description provided.

**Comment by yyked** [comment]
> 总要先做个检测/48小时亭太麻烦了，md，每天都去往下班，不是再回家，而是到子家捣乱，真的很烦人

请问你有找到这样的软件吗？

**Comment by ilovexjp** [comment]
这个每个省都不太一样，可以试试抓包改网络请求或者把源码弄下来自行部署
