### ISSUE TITLE
手机浏览器打开地址栏能不能隐藏掉？😂

### ISSUE THREAD

**Issue by solemnrex** [ilovexjp/trip-card#13]

**Comment by pzy2000** [comment]
用edge就行，往上拖一下

**Comment by ilovexjp** [comment]
现在可以添加到主屏幕了

- 在 Safari (iOS) 上，点击下方“分享”按钮，再点击“添加至主屏幕”
- 在 Chrome (Android) 上，点击右上角菜单按钮，再点击“添加至主屏幕”
- 在 Firefox (Android) 上，点击右上角菜单按钮，再点击“安装”
