### ISSUE TITLE
行程码字体更新

### ISSUE THREAD

**Issue by Tequilapapi0911** [ilovexjp/trip-card#16]
首先感谢包蜜owner，非常有用的项目，给你点一亿个赞❤️❤️❤️
最近发现两个问题：
1:仔细对比了一下最新版行程码发现上方手机号部分和下方7天内途径省份部分字体较粗较大，更新时间部分字体较细。
2:ios下载到桌面后打开下方有较大部分的空白。
希望老哥抽空更新，下周去外地考试就靠这个了🙏🙏🙏🙏

**Comment by ilovexjp** [comment]
本项目原本是从 Web 版源码修改而来，所以部分细节与微信小程序上的显示有差别。现已更新为微信小程序所使用的样式，未来也可能会加上小程序的 UI（导航栏）。
