### ISSUE TITLE
样式错误

### ISSUE THREAD

**Issue by LHW2019** [ilovexjp/trip-card#17]
在iPhone刘海屏设备上，将粤康码或行程卡以PWA应用添加到桌面后打开，状态栏的样式会出现底色不与微信小程序ui栏相同的情况![image](https://user-images.githubusercontent.com/34885163/198877422-e34b5aac-5613-4cbe-b454-dfbc0890b34a.jpeg)

**Comment by ilovexjp** [comment]
暂时没找到解决办法，可以试试先整体安装（在目录页面点击“添加至主屏幕”）

**Comment by kof8855** [comment]
好像没法手机全屏覆盖。有什么浏览器能全屏覆盖的
