### ISSUE TITLE
new style had changed

### ISSUE THREAD

**Issue by lxy826076** [ilovexjp/trip-card#2]
hi,the  style of trip card has be changed，can you update this code,thank you!

**Comment by ilovexjp** [comment]
I'm sorry but currently I haven't spotted any major change to the style, I would like to look into this if you could share some screenshots and shed a light on the differences, thank you.

**Comment by realliuweii** [comment]
> 

![IMG_20220614_003415](https://user-images.githubusercontent.com/47459942/173401793-dd77a7d4-bf06-43f3-ad6d-08babc7b6df2.jpg)
new style
