### ISSUE TITLE
行程卡已改为7天

### ISSUE THREAD

**Issue by error1ee** [ilovexjp/trip-card#6]
7月8日，“通信行程卡”微信公众号发布了关于调整“通信行程卡”査询结果覆盖时间范围的公告：根据《新型冠状病毒肺炎防控方案（第九版）》，即日起 “通信行程卡”查询结果的覆盖时间范围由“14天”调整为“7天”。

**Comment by ppooii12009** [comment]
+1 app部署页面记得更新

**Comment by ilovexjp** [comment]
界面已更新
